# Generated by Django 6.0.4 on 2026-04-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'actor', 'verbose_name_plural': 'actors'},
        ),
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
    ]
